### ISSUE TITLE
Is it normal for GPU usage to skyrocket when increasing fps cap?

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#14]
Info:

macOS Sonoma 14.5 (Apple M1)
AppleBlox 0.7.1

Yesterday, this wasn't an issue for me. I could increase the FPS cap, it'd work, and my GPU would stay at normal rates. But now whenever I increase the FPS cap, my GPU usage increases as well. I have reinstalled and restarted my device many times. Should I expect this to happen?

**Comment by OrigamingWasTaken** [comment]
Nothing has changed in the way AppleBlox work so this may be a roblox issue. I've heard rumors the FPS fast flag is deprecated but I'm not sure. I'll look into it.

**Comment by bdc0der** [comment]
Hmmm...well I've checked FPS testing games and it the flag seems to work fine (I can get around 250ish fps with it), but the surge in GPU usage is new. But thanks for looking into it.

**Comment by bdc0der** [comment]
I should of clarified, normally my GPU usage sits around 20-30%, but when I launch Roblox via Appleblox it skyrockets to 95-100%

**Comment by OrigamingWasTaken** [comment]
Oh, well maybe try to disable every fast flag and see if it fixes it

**Comment by bdc0der** [comment]
I tried disabling every flag, but it didn't fix it, unfortunately.

**Comment by bdc0der** [comment]
forgot to mention this happened a few days after I used hyperthreading (or maybe it was max threading) fast flag...

**Comment by OrigamingWasTaken** [comment]
Have you tried to reinstall Roblox?

**Comment by bdc0der** [comment]
Yes, I tried that, and the problem persists.

**Comment by OrigamingWasTaken** [comment]
Re on this issue, if you're using 0.7.1, it's maybe due to the fact that if your **Fps target** is over your screen's max refresh rate, it will automatically switch to Vulkan instead of metal.

**Comment by OrigamingWasTaken** [comment]
Was your issue resolved?

**Comment by bdc0der** [comment]
Well...not really. But since increasing the fps cap basically tells the computer to use more power...I don't think its really a problem with the app, just a constraint with how the function works. **I indeed have noticed that lowering the fps cap lowers the amount of GPU usage as well.**
