### ISSUE TITLE
Launching from browser URL doesn't work

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#16]
A few things I noticed about this (I'm using nightly build 7.1)

- When I try to launch Roblox normally without Appleblox via the website, appleblox opens up anyway. I have to enable and disable the support launching from the website toggle just so I can launch roblox normally from the website.
- When the toggle IS enabled, it doesn't detect that I have Roblox installed (roblox in my user applications folder, not the system folder)

**Comment by OrigamingWasTaken** [comment]
1. Yes, I'm currently reworking the system panel settings to be able to update the toggle and show if it's already enabled
2. What do you mean by don't detect? It doesn't launch?

**Comment by bdc0der** [comment]
2 - Yes, when I try to open it via the link, I get this error. This might be a result of Rblox being in my user applications folder instead of the system's, but I don't know. This also happens when I try to use the launch shortcut feature. 
<img width="249" alt="Screenshot 2024-09-15 at 8 30 56 AM" src="https://github.com/user-attachments/assets/78d78e5e-76df-4cd2-92d8-fac7a2e146dc">

**Comment by bdc0der** [comment]
/Users/(username)/Applications/Roblox.app

**Comment by OrigamingWasTaken** [comment]
I'm currently remaking the system to launch from the website so I hope this will be fixed. If not I will come back here.

**Comment by bdc0der** [comment]
Alright then, I eagerly await its release.
