### ISSUE TITLE
MacOS 10.15.7?

### ISSUE THREAD

**Issue by ItsAHotDog-cmd** [AppleBlox/appleblox#17]
Hi, me again and i just want to know if a backport of Appleblox for MacOS Catalina is in the works, or in progress.
Please let me know as soon as possible, thank you.

**Comment by OrigamingWasTaken** [comment]
Are you experimenting the famous white screen?

**Comment by ItsAHotDog-cmd** [comment]
Yes

**Comment by OrigamingWasTaken** [comment]
Do you have Discord? I want to debug this issue and it would be easier there.

**Comment by ItsAHotDog-cmd** [comment]
Yes I do, "ItsAHotDog"

**Comment by ItsAHotDog-cmd** [comment]
Oh wait
My bad, "Soviet HotDog"

**Comment by ItsAHotDog-cmd** [comment]
Hello?

**Comment by OrigamingWasTaken** [comment]
Can you add me instead (@Origaming)

**Comment by ItsAHotDog-cmd** [comment]
I sent a request, and yes my tag is “ItsAHotDog”

**Comment by TeamOrigaming** [comment]
Hello @ItsAHotDog-cmd 
Seems like you tag the wrong account. I'm just "origaming" while the one you wanted to tag is "OrigamingWasTaken"

**Comment by OrigamingWasTaken** [comment]
> Hello @ItsAHotDog-cmd 
> 
> Seems like you tag the wrong account. I'm just "origaming" while the one you wanted to tag is "OrigamingWasTaken"

Ah yes sorry, it was me when sending my discord tag

**Comment by OrigamingWasTaken** [comment]
For anyone encountering this issue, please see the chrome build of 0.7.1: https://nightly.link/AppleBlox/appleblox-chrome/workflows/build/main?preview

**Comment by OrigamingWasTaken** [comment]
NeutralinoJS window mode is incompatible with versions lower than MacOS 11.
However, I managed to include a workaround, that opens the app in the browser instead for those versions. The app should not work on lower MacOS versions.
