### ISSUE TITLE
Avatar Editor Mod Causing Roblox to Crash

### ISSUE THREAD

**Issue by ZeyadMused** [AppleBlox/appleblox#20]
I recently made a custom mod to change the avatar editor’s background in Roblox. After launching the game and navigating to the avatar tab, Roblox consistently crashes. Everything works fine when I disable the mod, but with it enabled, it causes the issue.

![Screenshot 2024-09-25 at 12 59 24 PM](https://github.com/user-attachments/assets/88958fac-6fdd-4d2c-848b-c6a872317767)

**Comment by OrigamingWasTaken** [comment]
Try to use your mod with [BloxMGR](https://github.com/sdhEmily/BloxMgr) and if it still crashes, it is something in your mod.

**Comment by OrigamingWasTaken** [comment]
No further context, and this is an issue with the mod, not appleblox
