### ISSUE TITLE
No Roblox app opening after leaving feature?

### ISSUE THREAD

**Issue by OrangesWhy** [AppleBlox/appleblox#24]
Can you add a feature that makes it so the Roblox app doesn't open after you leave?

**Comment by OrigamingWasTaken** [comment]
I will look into it

**Comment by OrangesWhy** [comment]
thanks

**Comment by OrigamingWasTaken** [comment]
This has been implemented in 0.8.0-dev.7 (will come out when 0.8.0 releases)
