### ISSUE TITLE
Contrast Issues

### ISSUE THREAD

**Issue by Christmaswreath** [AppleBlox/appleblox#30]
![image](https://github.com/user-attachments/assets/e6ed3a9e-7996-4b3a-a8b3-90d5386c9d9f)

**Comment by OrigamingWasTaken** [comment]
Fixed in 0.8.0

**Comment by Christmaswreath** [comment]
Where do I get 0.8.0?

**Comment by OrigamingWasTaken** [comment]
https://nightly.link/AppleBlox/appleblox/workflows/build/dev?preview

**Comment by Christmaswreath** [comment]
Please reopen - Icons are extremely close to the background color in 0.8.0-dev.14.
<img width="1262" alt="Screenshot 2024-10-26 at 2 23 16 PM" src="https://github.com/user-attachments/assets/3d762df0-b84f-452b-b627-195fcc4053b3">
