### ISSUE TITLE
Big Sur style icon for 0.8.0

### ISSUE THREAD

**Issue by Christmaswreath** [AppleBlox/appleblox#31]
[AppleBlox.icns.zip](https://github.com/user-attachments/files/17446803/AppleBlox.icns.zip)

**Comment by OrigamingWasTaken** [comment]
![CleanShot 2024-10-19 at 20 00 12@2x](https://github.com/user-attachments/assets/dc50d576-9bef-4051-8440-c5ca5089a3fe)
The goal of the current icon is to ressemble Roblox's one. The only thingy it may be lacking currently is a drop shadow.

**Comment by Christmaswreath** [comment]
Huh. The Roblox icon isn't the prettiest thing in the world. I can change it manually, but as of now, whenever I open the app the icon changes back to the default one. When I close the app, it goes back to the one I have made.

**Comment by 20ch** [comment]
Roblox and Appleblox logo's are good enough!
