### ISSUE TITLE
UI pops up that can't be closed

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#34]
When I open Appleblox 8.0 (or whatever version the nightly dev link downloads), this UI pops up. Since there's no way to resize Appleblox or close the UI, it effectively prevents me from using Appleblox.
<img width="1440" alt="Screenshot 2024-10-27 at 8 29 37 AM" src="https://github.com/user-attachments/assets/a281c1e9-f940-49ae-af66-9e15490232de">

**Comment by OrigamingWasTaken** [comment]
Yep :/
Couldn't really test that because the way updates work but to fix this you can just download the latest version from the website

**Comment by bdc0der** [comment]
The 8.0 dev version or the regular?

**Comment by OrigamingWasTaken** [comment]
The regular on the https://appleblox.com website or from the github releases

**Comment by bdc0der** [comment]
I don't suppose there's a way to export my fast flags some other way then the regular export button? I have a decent amount and don't want to lose them...

**Comment by OrigamingWasTaken** [comment]
You're using the 0.8.0 beta which is compatible with 0.8.0 so you will not loose any settings.

**Comment by bdc0der** [comment]
Just checked it now and it seems to be working well, thanks for the help.
