### ISSUE TITLE
No problem, just question

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#38]
I've recently been dabbling in Applescript to create a Application via script editor that auto opens roblox and then auto joins a game. 
**_**e.g.
do shell script "open 'roblox://navigation/share_links?code=26329d5b09019314822edf17ae4a4ff6&type=Server'"
(this opens my private server)**_**

I was wondering if it was possible to modify it so I could launch Roblox via Appleblox and then autojoin a game.

I'm not sure if this is part of your area of expertise or what, but I figured since you primarily made Appleblox you might have an idea or two or at least be able to point me in the right direction for finding one.

**Comment by OrigamingWasTaken** [comment]
Yes it's possible currently. Enable "Delegate launchin" in the Roblox panel inside AppleBlox.

Then in your script, open appleblox from the `appleblox://` url and then open the `roblox://` url after.

**Comment by bdc0der** [comment]
I might be doing this wrong. Would it look something like this?

do shell script "open 'appleblox://'"
delay 2
do shell script "open 'roblox://navigation/share_links?code=26329d5b09019314822edf17ae4a4ff6&type=Server'"

**Comment by OrigamingWasTaken** [comment]
Ah yes I think I know why. AppleBlox only handled `roblox-player` links. I will add support for launching from `roblox`.
