### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bdc0der** [AppleBlox/appleblox#39]
Before I suggest this, I'd just like to thank you for all the work you've done with this app. It's great how willing you are to make changes and update the app, and it's made my experience (namely in the way of performance) a lot better. 

Anyway, I was wondering if there's already a feature, switch, or something that automatically closes Appleblox when Roblox is closed (assuming the Roblox instance is launched via Appleblox). If not, I think that'd be a nice feature to add.

**Comment by OrigamingWasTaken** [comment]
Good idea. I will implement that.

**Comment by bdc0der** [comment]
Alright cool.

**Comment by OrigamingWasTaken** [comment]
Added in 0.8.4
