### ISSUE TITLE
AppleBox Crash with Pet Simulator 99 Roblox game multiple-instance

### ISSUE THREAD

**Issue by etiennegirardin** [AppleBlox/appleblox#46]
Hello, thank you for this app and the multi-instance feature. I am grateful it exists on MacOS.

I am using version 0.8.5 of AppleBox.

I get issues of repeated crashes of AppleBox app on MacOS Sequoia 16.1 with MacBook Pro M1 Pro, 16 GB Ram.

2 or 3 instances seem to be the maximum I am able to support, and even then AppleBox will eventually crash, usually within minutes.

Let me know if other infirmation is required. Thank you and regards.

**Comment by etiennegirardin** [comment]
Here is an export of my Applebox configuration zip file, as requested on the discord server.
[abloxconfig-0.8.5.zip](https://github.com/user-attachments/files/17759731/abloxconfig-0.8.5.zip)

I dont use any special setting to my knowledge.

**Comment by OrigamingWasTaken** [comment]
The Multi-Instance implementation of AppleBlox is very bad and rushed. You should use [this project](https://github.com/Insadem/multi-roblox-macos) which is written in Go and way more concrete.
