### ISSUE TITLE
my fps isnt unlocking

### ISSUE THREAD

**Issue by mozibites** [AppleBlox/appleblox#47]
Im on a Mac m1 sonoma
The issue is whenever I put my fps unlocker to the max when I launch roblox it simply doesn't uncap.I've tried everything and I followed the tutorial to appleblox.
Though it only works when I exit the window but when I go back in it quickly caps it back to 60

**Comment by TrisecTroop** [comment]
Use Roblox's own fps unlocker. To me it is better and works better than the one in Appleblox.

**Comment by OrigamingWasTaken** [comment]
> > Use Roblox's own fps unlocker. To me it is better and works better than the one in Appleblox.
> 
> The roblox one for me dosent work

You need to use vulkan
