### ISSUE TITLE
all of my flags say "invalid flags on selected profile"

### ISSUE THREAD

**Issue by ihavenofriendslol201** [AppleBlox/appleblox#52]
problem in the title
![image](https://github.com/user-attachments/assets/fa42159f-a233-4003-b7a5-111946be523f)

**Comment by ihavenofriendslol201** [comment]
here's the log
[2024-12-28_23-04-52_0.8.6.log](https://github.com/user-attachments/files/18267956/2024-12-28_23-04-52_0.8.6.log)

**Comment by OrigamingWasTaken** [comment]
It means that all flags listed in the popup don't exist anymore and that you should remove them because they have no effect on your game. SOME flags may appear invalid when they do in fact work, but that's rare.
