### ISSUE TITLE
mac os 10.9 support

### ISSUE THREAD

**Issue by REDRUMERRisCOOL** [AppleBlox/appleblox#55]
it may sound goofy but will there be a mac os maverics (10.9) support, because now the lowest version is high sierra (10.13)

**Comment by OrigamingWasTaken** [comment]
No sorry, there is no code framework supporting 10.9 as it is an extremely old version.

**Comment by ok-coder1** [comment]
> No sorry, there is no code framework supporting 10.9 as it is an extremely old version.

What about macOS Sierra 10.12.6? It's the version just before macOS High Sierra 10.13.
(I can install macOS High Sierra 10.13, it's just that I can't login to my Apple Account (formerly Apple ID) because it requires 10.13, and I'm logging in to install 10.13.)

**Comment by OrigamingWasTaken** [comment]
Nothing under 10.13 will be supported and 10.13 doesn't even always work.
