### ISSUE TITLE
App not loading on OSX <12

### ISSUE THREAD

**Issue by ItsAHotDog-cmd** [AppleBlox/appleblox#9]
On launch plain white screen(does not change).

**Comment by OrigamingWasTaken** [comment]
Can you link a screenshot?

**Comment by ItsAHotDog-cmd** [comment]
![Screen Shot 2024-08-10 at 9 13 30 AM](https://github.com/user-attachments/assets/457de646-d54b-42cd-ba65-587a4e9d9048)

**Comment by ItsAHotDog-cmd** [comment]
> ![Screen Shot 2024-08-10 at 9 13 30 AM](https://private-user-images.githubusercontent.com/177986197/356816718-457de646-d54b-42cd-ba65-587a4e9d9048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTk1MjksIm5iZiI6MTcyMzI5OTIyOSwicGF0aCI6Ii8xNzc5ODYxOTcvMzU2ODE2NzE4LTQ1N2RlNjQ2LWQ1NGItNDJjZC1iYTY1LTU4N2E0ZTlkOTA0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxNDEzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTQzZWU2MTdmNzFhYzRjMGUwMjU1ZDhjYTczMTYxMGQ1ZWY1NmQ1ZWFkNDU2ZTVkMTU4NDM0MDI1MDczZjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t_n_mLA-pnOnfuH_H0oOZQFyOW7CY1PXn4OkLCWI_FE)

It stays like this.

**Comment by OrigamingWasTaken** [comment]
Where did you download the app? Also what version?

**Comment by ItsAHotDog-cmd** [comment]
Ive tried every version, ARM64, Universal, Bit, even every version of the app. It wont load.

**Comment by ItsAHotDog-cmd** [comment]
Oh yes, I downloaded the app from here.

**Comment by OrigamingWasTaken** [comment]
Okay... Can you give me details about your Mac? Also I will only be able to help further later because I currently don't have access to my Mac.

**Comment by ItsAHotDog-cmd** [comment]
My Mac is a 2013 iMac and the OS is 10.15.7

**Comment by OrigamingWasTaken** [comment]
Ah that may be the problem. I think I compiled some librairies for min MacOS 12... I'll try to see later if that's the case.

And maybe make a special version for older MacOS versions.

**Comment by ItsAHotDog-cmd** [comment]
Ok thank you!

**Comment by ItsAHotDog-cmd** [comment]
If you do decide to make a version for older Mac's could you let me know?

**Comment by OrigamingWasTaken** [comment]
Let's take this to #17 as it's more active.
